from PyQt5 import QtCore, QtWidgets
from data import Data


class BaseUI(object):
    def setupUi(self, Tab,id,MainWindow):
        self.bandData(id)
        Tab.baseUI=self
        Tab.setObjectName("Tab")
        Tab.resize(853, 478)
        self.gridLayout = QtWidgets.QGridLayout(Tab)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Tab)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(12, 27, 641, 41))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setHorizontalSpacing(30)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.ID = QtWidgets.QLabel(self.groupBox_2)
        self.ID.setObjectName("ID")
        self.gridLayout_6.addWidget(self.ID, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 2, 1, 1)
        self.name = QtWidgets.QLabel(self.groupBox_2)
        self.name.setObjectName("name")
        self.gridLayout_6.addWidget(self.name, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 4, 1, 1)
        self.capacity = QtWidgets.QLabel(self.groupBox_2)
        self.capacity.setObjectName("capacity")
        self.gridLayout_6.addWidget(self.capacity, 0, 5, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 80, 791, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setHorizontalSpacing(20)
        self.gridLayout_4.setVerticalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.consume_coal_1 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_coal_1.setObjectName("consume_coal_1")
        self.gridLayout_4.addWidget(self.consume_coal_1, 1, 5, 1, 1)
        self.input_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_4.setObjectName("input_4")
        self.gridLayout_4.addWidget(self.input_4, 4, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 1, 1, 1)
        self.consume_1 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_1.setObjectName("consume_1")
        self.gridLayout_4.addWidget(self.consume_1, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 4, 1, 1)
        self.input_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_1.setObjectName("input_1")
        self.gridLayout_4.addWidget(self.input_1, 1, 3, 1, 1)
        self.load_4 = QtWidgets.QLabel(self.groupBox_3)
        self.load_4.setObjectName("load_4")
        self.gridLayout_4.addWidget(self.load_4, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 3, 1, 1)
        self.consume_2 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_2.setObjectName("consume_2")
        self.gridLayout_4.addWidget(self.consume_2, 2, 1, 1, 1)
        self.load_1 = QtWidgets.QLabel(self.groupBox_3)
        self.load_1.setObjectName("load_1")
        self.gridLayout_4.addWidget(self.load_1, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.input_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_2.setObjectName("input_2")
        self.gridLayout_4.addWidget(self.input_2, 2, 3, 1, 1)
        self.load_3 = QtWidgets.QLabel(self.groupBox_3)
        self.load_3.setObjectName("load_3")
        self.gridLayout_4.addWidget(self.load_3, 3, 0, 1, 1)
        self.consume_4 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_4.setObjectName("consume_4")
        self.gridLayout_4.addWidget(self.consume_4, 4, 1, 1, 1)
        self.input_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.input_3.setObjectName("input_3")
        self.gridLayout_4.addWidget(self.input_3, 3, 3, 1, 1)
        self.state_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.state_4.setObjectName("state_4")
        self.state_4.addItem("")
        self.state_4.addItem("")
        self.state_4.addItem("")
        self.gridLayout_4.addWidget(self.state_4, 4, 2, 1, 1)
        self.power_self_1 = QtWidgets.QLabel(self.groupBox_3)
        self.power_self_1.setObjectName("power_self_1")
        self.gridLayout_4.addWidget(self.power_self_1, 1, 4, 1, 1)
        self.state_1 = QtWidgets.QComboBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state_1.sizePolicy().hasHeightForWidth())
        self.state_1.setSizePolicy(sizePolicy)
        self.state_1.setMinimumSize(QtCore.QSize(0, 10))
        self.state_1.setObjectName("state_1")
        self.state_1.addItem("")
        self.state_1.addItem("")
        self.state_1.addItem("")
        self.gridLayout_4.addWidget(self.state_1, 1, 2, 1, 1)
        self.power_self_3 = QtWidgets.QLabel(self.groupBox_3)
        self.power_self_3.setObjectName("power_self_3")
        self.gridLayout_4.addWidget(self.power_self_3, 3, 4, 1, 1)
        self.power_self_2 = QtWidgets.QLabel(self.groupBox_3)
        self.power_self_2.setObjectName("power_self_2")
        self.gridLayout_4.addWidget(self.power_self_2, 2, 4, 1, 1)
        self.consume_3 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_3.setObjectName("consume_3")
        self.gridLayout_4.addWidget(self.consume_3, 3, 1, 1, 1)
        self.load_2 = QtWidgets.QLabel(self.groupBox_3)
        self.load_2.setObjectName("load_2")
        self.gridLayout_4.addWidget(self.load_2, 2, 0, 1, 1)
        self.state_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.state_3.setObjectName("state_3")
        self.state_3.addItem("")
        self.state_3.addItem("")
        self.state_3.addItem("")
        self.gridLayout_4.addWidget(self.state_3, 3, 2, 1, 1)
        self.power_self_4 = QtWidgets.QLabel(self.groupBox_3)
        self.power_self_4.setObjectName("power_self_4")
        self.gridLayout_4.addWidget(self.power_self_4, 4, 4, 1, 1)
        self.state_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.state_2.setObjectName("state_2")
        self.state_2.addItem("")
        self.state_2.addItem("")
        self.state_2.addItem("")
        self.gridLayout_4.addWidget(self.state_2, 2, 2, 1, 1)
        self.consume_coal_2 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_coal_2.setObjectName("consume_coal_2")
        self.gridLayout_4.addWidget(self.consume_coal_2, 2, 5, 1, 1)
        self.consume_coal_3 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_coal_3.setObjectName("consume_coal_3")
        self.gridLayout_4.addWidget(self.consume_coal_3, 3, 5, 1, 1)
        self.consume_coal_4 = QtWidgets.QLabel(self.groupBox_3)
        self.consume_coal_4.setObjectName("consume_coal_4")
        self.gridLayout_4.addWidget(self.consume_coal_4, 4, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 310, 281, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setObjectName("label_33")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.power_all = QtWidgets.QLabel(self.groupBox_4)
        self.power_all.setObjectName("power_all")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.power_all)
        self.label_35 = QtWidgets.QLabel(self.groupBox_4)
        self.label_35.setObjectName("label_35")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.coal_all = QtWidgets.QLabel(self.groupBox_4)
        self.coal_all.setObjectName("coal_all")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.coal_all)
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setObjectName("label_37")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.average_coal = QtWidgets.QLabel(self.groupBox_4)
        self.average_coal.setObjectName("average_coal")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.average_coal)
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.retranslateUi(Tab)
        QtCore.QMetaObject.connectSlotsByName(Tab)
        self.input_1.editingFinished.connect(lambda: self.updateBaseUI(1, self.input_1.text(),MainWindow))
        self.input_2.editingFinished.connect(lambda: self.updateBaseUI(2, self.input_2.text(),MainWindow))
        self.input_3.editingFinished.connect(lambda: self.updateBaseUI(3, self.input_3.text(),MainWindow))
        self.input_4.editingFinished.connect(lambda: self.updateBaseUI(4, self.input_4.text(),MainWindow))

    def retranslateUi(self, Tab):
        _translate = QtCore.QCoreApplication.translate
        Tab.setWindowTitle(_translate("Tab", "Tab"))
        self.groupBox.setTitle(_translate("Tab", "基本信息"))
        self.label.setText(_translate("Tab", "编号"))
        self.ID.setText(_translate("Tab", Tab.baseUI.data.id))
        self.label_3.setText(_translate("Tab", "机组型式"))
        self.name.setText(_translate("Tab", Tab.baseUI.data.name))
        self.label_5.setText(_translate("Tab", "装机总量"))
        self.capacity.setText(_translate("Tab", '%d'%Tab.baseUI.data.capacity))
        self.groupBox_3.setTitle(_translate("Tab", "参数"))
        self.consume_coal_1.setText(_translate("Tab", "0"))
        self.label_22.setText(_translate("Tab", "煤耗"))
        self.consume_1.setText(_translate("Tab", '%d'%Tab.baseUI.data.consume_1))
        self.label_8.setText(_translate("Tab", "每种负荷的煤耗（吨）"))
        self.label_25.setText(_translate("Tab", "每种负荷的发电量（GWh）"))
        self.load_4.setText(_translate("Tab", "0.4"))
        self.label_20.setText(_translate("Tab", "运行状态"))
        self.label_21.setText(_translate("Tab", "运行时长"))
        self.consume_2.setText(_translate("Tab", '%d'%Tab.baseUI.data.consume_2))
        self.load_1.setText(_translate("Tab", "1"))
        self.label_23.setText(_translate("Tab", "负荷"))
        self.load_3.setText(_translate("Tab", "0.5"))
        self.consume_4.setText(_translate("Tab", '%d'%Tab.baseUI.data.consume_4))
        self.state_4.setItemText(0, _translate("Tab", "100%负荷运行时间"))
        self.state_4.setItemText(1, _translate("Tab", "75%负荷运行时间"))
        self.state_4.setItemText(2, _translate("Tab", "50%负荷运行时间"))
        self.power_self_1.setText(_translate("Tab", "0"))
        self.state_1.setItemText(0, _translate("Tab", "100%负荷运行时间"))
        self.state_1.setItemText(1, _translate("Tab", "75%负荷运行时间"))
        self.state_1.setItemText(2, _translate("Tab", "50%负荷运行时间"))
        self.power_self_3.setText(_translate("Tab", "0"))
        self.power_self_2.setText(_translate("Tab", "0"))
        self.consume_3.setText(_translate("Tab", '%d'%Tab.baseUI.data.consume_3))
        self.load_2.setText(_translate("Tab", "0.75"))
        self.state_3.setItemText(0, _translate("Tab", "100%负荷运行时间"))
        self.state_3.setItemText(1, _translate("Tab", "75%负荷运行时间"))
        self.state_3.setItemText(2, _translate("Tab", "50%负荷运行时间"))
        self.power_self_4.setText(_translate("Tab", "0"))
        self.state_2.setItemText(0, _translate("Tab", "100%负荷运行时间"))
        self.state_2.setItemText(1, _translate("Tab", "75%负荷运行时间"))
        self.state_2.setItemText(2, _translate("Tab", "50%负荷运行时间"))
        self.consume_coal_2.setText(_translate("Tab", "0"))
        self.consume_coal_3.setText(_translate("Tab", "0"))
        self.consume_coal_4.setText(_translate("Tab", "0"))
        self.groupBox_4.setTitle(_translate("Tab", "统计"))
        self.label_33.setText(_translate("Tab", "总发电量（GWh）"))
        self.power_all.setText(_translate("Tab", "0"))
        self.label_35.setText(_translate("Tab", "总煤耗（吨）"))
        self.coal_all.setText(_translate("Tab", "0"))
        self.label_37.setText(_translate("Tab", "年平均供电煤耗"))
        self.average_coal.setText(_translate("Tab", "0"))

    def updateBaseUI(self, state, input,MainWindow):
        if input=='':
            return
        self.data.calculate_power(state,int(input))

        self.power_self_1.setText('%d'%self.data.power_self_1)
        self.power_self_2.setText('%d'%self.data.power_self_2)
        self.power_self_3.setText('%d'%self.data.power_self_3)
        self.power_self_4.setText('%d'%self.data.power_self_4)
        self.consume_coal_1.setText('%d'%self.data.consume_coal_1)
        self.consume_coal_2.setText('%d'%self.data.consume_coal_2)
        self.consume_coal_3.setText('%d'%self.data.consume_coal_3)
        self.consume_coal_4.setText('%d'%self.data.consume_coal_4)
        self.power_all.setText('%d'%self.data.power_all)
        self.coal_all.setText('%d'%self.data.coal_all)
        self.average_coal.setText('%d'%self.data.average_coal)

        MainWindow.formView.widget.updateForm(MainWindow.dataTab)



    def bandData(self, id):
        if id == '0':
            self.data = Data('0', "1000MW级超超临界湿冷", 58280, 282, 286, 303, 322)
        elif id == '1':
            self.data = Data('1', "1000MW级超超临界空冷", 2120, 305, 310, 327, 340)
        elif id == '2':
            self.data = Data('2', "600MW级超超临界湿冷", 20780, 289, 294, 311, 328)
        elif id == '3':
            self.data = Data('3', "600MW级超超临界空冷", 1320, 307, 311, 322, 330)
        elif id == '4':
            self.data = Data('4', "600MW级超临界湿冷", 100190, 300, 304, 322, 343)
        elif id == '5':
            self.data = Data('5', "600MW级超临界空冷", 21060, 320, 326, 341, 352)
        elif id == '6':
            self.data = Data('6', "600MW级亚临界湿冷", 89180, 312, 317, 334, 353)
        elif id == '7':
            self.data = Data('7', "600MW级亚临界空冷", 33746, 330, 336, 358, 384)
        elif id == '8':
            self.data = Data('8', "300MW级超临界湿冷", 5780, 310, 316, 332, 344)
        elif id == '9':
            self.data = Data('9', "300MW级超临界空冷", 4100, 332, 338, 353, 366)
        elif id == '10':
            self.data = Data('10', "300MW级亚临界湿冷", 197422, 324, 330, 349, 373)
        elif id == '11':
            self.data = Data('11', "300MW级亚临界空冷", 37140, 340, 346, 366, 390)
