from PyQt5 import QtCore, QtWidgets


class Form(QtWidgets.QWidget):
    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setObjectName("Form")
        self.resize(991, 748)
        self.groupBox_3 = QtWidgets.QGroupBox(self)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 571, 571))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 541, 419))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.power_all_4 = QtWidgets.QLabel(self.groupBox)
        self.power_all_4.setText("")
        self.power_all_4.setObjectName("power_all_4")
        self.gridLayout.addWidget(self.power_all_4, 5, 2, 1, 1)
        self.name_8 = QtWidgets.QLabel(self.groupBox)
        self.name_8.setText("")
        self.name_8.setObjectName("name_8")
        self.gridLayout.addWidget(self.name_8, 9, 1, 1, 1)
        self.ID_6 = QtWidgets.QLabel(self.groupBox)
        self.ID_6.setObjectName("ID_6")
        self.gridLayout.addWidget(self.ID_6, 7, 0, 1, 1)
        self.power_all_1 = QtWidgets.QLabel(self.groupBox)
        self.power_all_1.setText("")
        self.power_all_1.setObjectName("power_all_1")
        self.gridLayout.addWidget(self.power_all_1, 2, 2, 1, 1)
        self.ID_2 = QtWidgets.QLabel(self.groupBox)
        self.ID_2.setObjectName("ID_2")
        self.gridLayout.addWidget(self.ID_2, 3, 0, 1, 1)
        self.name_2 = QtWidgets.QLabel(self.groupBox)
        self.name_2.setText("")
        self.name_2.setObjectName("name_2")
        self.gridLayout.addWidget(self.name_2, 3, 1, 1, 1)
        self.ID_11 = QtWidgets.QLabel(self.groupBox)
        self.ID_11.setObjectName("ID_11")
        self.gridLayout.addWidget(self.ID_11, 12, 0, 1, 1)
        self.ID_8 = QtWidgets.QLabel(self.groupBox)
        self.ID_8.setObjectName("ID_8")
        self.gridLayout.addWidget(self.ID_8, 9, 0, 1, 1)
        self.ID_3 = QtWidgets.QLabel(self.groupBox)
        self.ID_3.setObjectName("ID_3")
        self.gridLayout.addWidget(self.ID_3, 4, 0, 1, 1)
        self.name_3 = QtWidgets.QLabel(self.groupBox)
        self.name_3.setText("")
        self.name_3.setObjectName("name_3")
        self.gridLayout.addWidget(self.name_3, 4, 1, 1, 1)
        self.name_7 = QtWidgets.QLabel(self.groupBox)
        self.name_7.setText("")
        self.name_7.setObjectName("name_7")
        self.gridLayout.addWidget(self.name_7, 8, 1, 1, 1)
        self.coal_all_8 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_8.setText("")
        self.coal_all_8.setObjectName("coal_all_8")
        self.gridLayout.addWidget(self.coal_all_8, 10, 3, 1, 1)
        self.ID_9 = QtWidgets.QLabel(self.groupBox)
        self.ID_9.setObjectName("ID_9")
        self.gridLayout.addWidget(self.ID_9, 10, 0, 1, 1)
        self.ID_7 = QtWidgets.QLabel(self.groupBox)
        self.ID_7.setObjectName("ID_7")
        self.gridLayout.addWidget(self.ID_7, 8, 0, 1, 1)
        self.ID_10 = QtWidgets.QLabel(self.groupBox)
        self.ID_10.setObjectName("ID_10")
        self.gridLayout.addWidget(self.ID_10, 11, 0, 1, 1)
        self.name_9 = QtWidgets.QLabel(self.groupBox)
        self.name_9.setText("")
        self.name_9.setObjectName("name_9")
        self.gridLayout.addWidget(self.name_9, 10, 1, 1, 1)
        self.power_all_5 = QtWidgets.QLabel(self.groupBox)
        self.power_all_5.setText("")
        self.power_all_5.setObjectName("power_all_5")
        self.gridLayout.addWidget(self.power_all_5, 6, 2, 1, 1)
        self.coal_all_10 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_10.setText("")
        self.coal_all_10.setObjectName("coal_all_10")
        self.gridLayout.addWidget(self.coal_all_10, 12, 3, 1, 1)
        self.coal_all_3 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_3.setText("")
        self.coal_all_3.setObjectName("coal_all_3")
        self.gridLayout.addWidget(self.coal_all_3, 5, 3, 1, 1)
        self.coal_all_1 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_1.setText("")
        self.coal_all_1.setObjectName("coal_all_1")
        self.gridLayout.addWidget(self.coal_all_1, 2, 3, 1, 1)
        self.ID_4 = QtWidgets.QLabel(self.groupBox)
        self.ID_4.setObjectName("ID_4")
        self.gridLayout.addWidget(self.ID_4, 5, 0, 1, 1)
        self.name_5 = QtWidgets.QLabel(self.groupBox)
        self.name_5.setText("")
        self.name_5.setObjectName("name_5")
        self.gridLayout.addWidget(self.name_5, 6, 1, 1, 1)
        self.coal_all_2 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_2.setText("")
        self.coal_all_2.setObjectName("coal_all_2")
        self.gridLayout.addWidget(self.coal_all_2, 3, 3, 1, 1)
        self.coal_all_0 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_0.setText("")
        self.coal_all_0.setObjectName("coal_all_0")
        self.gridLayout.addWidget(self.coal_all_0, 1, 3, 1, 1)
        self.power_all_3 = QtWidgets.QLabel(self.groupBox)
        self.power_all_3.setText("")
        self.power_all_3.setObjectName("power_all_3")
        self.gridLayout.addWidget(self.power_all_3, 4, 2, 1, 1)
        self.ID_1 = QtWidgets.QLabel(self.groupBox)
        self.ID_1.setText("")
        self.ID_1.setObjectName("ID_1")
        self.gridLayout.addWidget(self.ID_1, 2, 0, 1, 1)
        self.power_all_9 = QtWidgets.QLabel(self.groupBox)
        self.power_all_9.setText("")
        self.power_all_9.setObjectName("power_all_9")
        self.gridLayout.addWidget(self.power_all_9, 10, 2, 1, 1)
        self.name_0 = QtWidgets.QLabel(self.groupBox)
        self.name_0.setObjectName("name_0")
        self.gridLayout.addWidget(self.name_0, 1, 1, 1, 1)
        self.coal_all_7 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_7.setText("")
        self.coal_all_7.setObjectName("coal_all_7")
        self.gridLayout.addWidget(self.coal_all_7, 9, 3, 1, 1)
        self.coal_all_9 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_9.setText("")
        self.coal_all_9.setObjectName("coal_all_9")
        self.gridLayout.addWidget(self.coal_all_9, 11, 3, 1, 1)
        self.coal_all_4 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_4.setText("")
        self.coal_all_4.setObjectName("coal_all_4")
        self.gridLayout.addWidget(self.coal_all_4, 6, 3, 1, 1)
        self.coal_all_6 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_6.setText("")
        self.coal_all_6.setObjectName("coal_all_6")
        self.gridLayout.addWidget(self.coal_all_6, 8, 3, 1, 1)
        self.coal_all_5 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_5.setText("")
        self.coal_all_5.setObjectName("coal_all_5")
        self.gridLayout.addWidget(self.coal_all_5, 7, 3, 1, 1)
        self.power_all_6 = QtWidgets.QLabel(self.groupBox)
        self.power_all_6.setText("")
        self.power_all_6.setObjectName("power_all_6")
        self.gridLayout.addWidget(self.power_all_6, 7, 2, 1, 1)
        self.name_1 = QtWidgets.QLabel(self.groupBox)
        self.name_1.setText("")
        self.name_1.setObjectName("name_1")
        self.gridLayout.addWidget(self.name_1, 2, 1, 1, 1)
        self.power_all_10 = QtWidgets.QLabel(self.groupBox)
        self.power_all_10.setText("")
        self.power_all_10.setObjectName("power_all_10")
        self.gridLayout.addWidget(self.power_all_10, 11, 2, 1, 1)
        self.ID_0 = QtWidgets.QLabel(self.groupBox)
        self.ID_0.setText("")
        self.ID_0.setObjectName("ID_0")
        self.gridLayout.addWidget(self.ID_0, 1, 0, 1, 1)
        self.ID_5 = QtWidgets.QLabel(self.groupBox)
        self.ID_5.setObjectName("ID_5")
        self.gridLayout.addWidget(self.ID_5, 6, 0, 1, 1)
        self.name_11 = QtWidgets.QLabel(self.groupBox)
        self.name_11.setText("")
        self.name_11.setObjectName("name_11")
        self.gridLayout.addWidget(self.name_11, 12, 1, 1, 1)
        self.name_6 = QtWidgets.QLabel(self.groupBox)
        self.name_6.setText("")
        self.name_6.setObjectName("name_6")
        self.gridLayout.addWidget(self.name_6, 7, 1, 1, 1)
        self.name_10 = QtWidgets.QLabel(self.groupBox)
        self.name_10.setText("")
        self.name_10.setObjectName("name_10")
        self.gridLayout.addWidget(self.name_10, 11, 1, 1, 1)
        self.power_all_8 = QtWidgets.QLabel(self.groupBox)
        self.power_all_8.setText("")
        self.power_all_8.setObjectName("power_all_8")
        self.gridLayout.addWidget(self.power_all_8, 9, 2, 1, 1)
        self.power_all_11 = QtWidgets.QLabel(self.groupBox)
        self.power_all_11.setText("")
        self.power_all_11.setObjectName("power_all_11")
        self.gridLayout.addWidget(self.power_all_11, 12, 2, 1, 1)
        self.power_all_0 = QtWidgets.QLabel(self.groupBox)
        self.power_all_0.setText("")
        self.power_all_0.setObjectName("power_all_0")
        self.gridLayout.addWidget(self.power_all_0, 1, 2, 1, 1)
        self.power_all_2 = QtWidgets.QLabel(self.groupBox)
        self.power_all_2.setText("")
        self.power_all_2.setObjectName("power_all_2")
        self.gridLayout.addWidget(self.power_all_2, 3, 2, 1, 1)
        self.name_4 = QtWidgets.QLabel(self.groupBox)
        self.name_4.setText("")
        self.name_4.setObjectName("name_4")
        self.gridLayout.addWidget(self.name_4, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.power_all_7 = QtWidgets.QLabel(self.groupBox)
        self.power_all_7.setText("")
        self.power_all_7.setObjectName("power_all_7")
        self.gridLayout.addWidget(self.power_all_7, 8, 2, 1, 1)
        self.coal_all_11 = QtWidgets.QLabel(self.groupBox)
        self.coal_all_11.setText("")
        self.coal_all_11.setObjectName("coal_all_11")
        self.gridLayout.addWidget(self.coal_all_11, 4, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 440, 211, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_49 = QtWidgets.QLabel(self.groupBox_2)
        self.label_49.setObjectName("label_49")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.power_all = QtWidgets.QLabel(self.groupBox_2)
        self.power_all.setText("")
        self.power_all.setObjectName("power_all")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.power_all)
        self.label_51 = QtWidgets.QLabel(self.groupBox_2)
        self.label_51.setObjectName("label_51")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        self.label_52.setObjectName("label_52")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.coal_all = QtWidgets.QLabel(self.groupBox_2)
        self.coal_all.setText("")
        self.coal_all.setObjectName("coal_all")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.coal_all)
        self.average_coal = QtWidgets.QLabel(self.groupBox_2)
        self.average_coal.setText("")
        self.average_coal.setObjectName("average_coal")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.average_coal)
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self)
        self.groupBox_4.setGeometry(QtCore.QRect(610, 10, 341, 571))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 90, 321, 261))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.group_power_1 = QtWidgets.QLabel(self.groupBox_5)
        self.group_power_1.setText("")
        self.group_power_1.setObjectName("group_power_1")
        self.gridLayout_5.addWidget(self.group_power_1, 2, 2, 1, 1)
        self.group_power_0 = QtWidgets.QLabel(self.groupBox_5)
        self.group_power_0.setText("")
        self.group_power_0.setObjectName("group_power_0")
        self.gridLayout_5.addWidget(self.group_power_0, 1, 2, 1, 1)
        self.group_coal_0 = QtWidgets.QLabel(self.groupBox_5)
        self.group_coal_0.setText("")
        self.group_coal_0.setObjectName("group_coal_0")
        self.gridLayout_5.addWidget(self.group_coal_0, 1, 1, 1, 1)
        self.group_coal_2 = QtWidgets.QLabel(self.groupBox_5)
        self.group_coal_2.setText("")
        self.group_coal_2.setObjectName("group_coal_2")
        self.gridLayout_5.addWidget(self.group_coal_2, 3, 1, 1, 1)
        self.group_power_2 = QtWidgets.QLabel(self.groupBox_5)
        self.group_power_2.setText("")
        self.group_power_2.setObjectName("group_power_2")
        self.gridLayout_5.addWidget(self.group_power_2, 3, 2, 1, 1)
        self.group_coal_1 = QtWidgets.QLabel(self.groupBox_5)
        self.group_coal_1.setText("")
        self.group_coal_1.setObjectName("group_coal_1")
        self.gridLayout_5.addWidget(self.group_coal_1, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(100, 430, 211, 141))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(15)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_50 = QtWidgets.QLabel(self.groupBox_6)
        self.label_50.setObjectName("label_50")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.group_power_all = QtWidgets.QLabel(self.groupBox_6)
        self.group_power_all.setText("")
        self.group_power_all.setObjectName("group_power_all")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.group_power_all)
        self.label_53 = QtWidgets.QLabel(self.groupBox_6)
        self.label_53.setObjectName("label_53")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.label_54 = QtWidgets.QLabel(self.groupBox_6)
        self.label_54.setObjectName("label_54")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.group_coal_all = QtWidgets.QLabel(self.groupBox_6)
        self.group_coal_all.setText("")
        self.group_coal_all.setObjectName("group_coal_all")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.group_coal_all)
        self.group_average_coal = QtWidgets.QLabel(self.groupBox_6)
        self.group_average_coal.setText("")
        self.group_average_coal.setObjectName("group_average_coal")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.group_average_coal)
        self.gridLayout_6.addLayout(self.formLayout_2, 0, 0, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "总览"))
        self.label_3.setText(_translate("Form", "总发电量（GWh）"))
        self.label_4.setText(_translate("Form", "总煤耗（吨）"))
        self.groupBox_2.setTitle(_translate("Form", "总计"))
        self.label_49.setText(_translate("Form", "总发电量"))
        self.label_51.setText(_translate("Form", "总煤耗"))
        self.label_52.setText(_translate("Form", "平均煤耗"))
        self.groupBox_4.setTitle(_translate("Form", "分类"))
        self.label_7.setText(_translate("Form", "超超"))
        self.label_9.setText(_translate("Form", "总煤耗（吨）"))
        self.label_8.setText(_translate("Form", "超"))
        self.label_5.setText(_translate("Form", "亚"))
        self.label_10.setText(_translate("Form", "总发电量（GWh）"))
        self.groupBox_6.setTitle(_translate("Form", "总计"))
        self.label_50.setText(_translate("Form", "总发电量"))
        self.label_53.setText(_translate("Form", "总煤耗"))
        self.label_54.setText(_translate("Form", "平均煤耗"))


    def updateForm(self, tabData):
        self.power_all.setText("0")
        self.coal_all.setText("0")
        self.average_coal.setText("0")
        self.group_power_all.setText("0")
        self.group_coal_all.setText("0")
        self.group_average_coal.setText("0")
        self.group_coal_0.setText("0")
        self.group_coal_1.setText("0")
        self.group_coal_2.setText("0")
        self.group_power_0.setText("0")
        self.group_power_1.setText("0")
        self.group_power_2.setText("0")
        for i in range(12):
            eval("self.ID_"+'%d'%i).setText("")
            eval("self.name_" + '%d' % i).setText("")
            eval("self.power_all_" + '%d' % i).setText("")
            eval("self.coal_all_" + '%d' % i).setText("")

        if len(tabData)==0:
            return

        j=0
        for i in range(12):
            for temp in tabData:
                data=temp.baseUI.data
                if(data.id=='%d'%i):
                    eval("self.ID_"+'%d'%j).setText(data.id)
                    eval("self.name_" + '%d' % j).setText(data.name)
                    eval("self.power_all_" + '%d' % j).setText('%d'%data.power_all)
                    eval("self.coal_all_" + '%d' % j).setText('%d'%data.coal_all)
                    self.power_all.setText('%d'%(int(self.power_all.text())+data.power_all))
                    self.coal_all.setText('%d'%(int(self.coal_all.text())+data.coal_all))
                    j=j+1
        self.average_coal.setText('%d'%(int(self.coal_all.text())/int(self.power_all.text())))



        for i in [0,1,2,3]:
            for temp in tabData:
                data=temp.baseUI.data
                if(data.id=='%d'%i):
                    self.group_power_0.setText('%d'%(int(self.group_power_0.text())+data.power_all))
                    self.group_coal_0.setText('%d'%(int(self.group_coal_0.text())+data.coal_all))

        for i in [4,5,6,7]:
            for temp in tabData:
                data=temp.baseUI.data
                if(data.id=='%d'%i):
                    self.group_power_1.setText('%d'%(int(self.group_power_1.text())+data.power_all))
                    self.group_coal_1.setText('%d'%(int(self.group_coal_1.text())+data.coal_all))

        for i in [8,9,10,11]:
            for temp in tabData:
                data=temp.baseUI.data
                if(data.id=='%d'%i):
                    self.group_power_2.setText('%d'%(int(self.group_power_2.text())+data.power_all))
                    self.group_coal_2.setText('%d'%(int(self.group_coal_2.text())+data.coal_all))

        self.group_power_all.setText('%d'%(int(self.group_power_0.text())+int(self.group_power_1.text())+int(self.group_power_2.text())))
        self.group_coal_all.setText('%d' % (int(self.group_coal_0.text()) + int(self.group_coal_1.text()) + int(self.group_coal_2.text())))
        self.group_average_coal.setText('%d'%(int(self.group_coal_all.text())/int(self.group_power_all.text())))